<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <AssemblyName>OpenUtau.Plugin.PtBrBrapa</AssemblyName>
  </PropertyGroup>

  <ItemGroup Condition="'$(GITHUB_ACTIONS)' != 'true' and Exists('/Applications/OpenUtau.app/Contents/MacOS/OpenUtau.Core.dll')">
    <Reference Include="OpenUtau.Core">
      <HintPath>/Applications/OpenUtau.app/Contents/MacOS/OpenUtau.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="YamlDotNet">
      <HintPath>/Applications/OpenUtau.app/Contents/MacOS/YamlDotNet.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(GITHUB_ACTIONS)' == 'true' or !Exists('/Applications/OpenUtau.app/Contents/MacOS/OpenUtau.Core.dll')">
    <Reference Include="OpenUtau.Core">
      <HintPath>libs/OpenUtau.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="YamlDotNet">
      <HintPath>libs/YamlDotNet.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
